/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Buidler Documentation",
  "tagline": "Buidler is a web3 messaging app for your community, teams, and supporters to connect, communicate and collaborate",
  "url": "https://docs.buidler.app",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/logo.svg",
  "organizationName": "buidlerfoundation",
  "projectName": "buidler-documentation",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/mac/buidler-documentation/sidebars.js",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": [
            "/Users/mac/buidler-documentation/src/css/custom.css"
          ]
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Buidler",
      "hideOnScroll": true,
      "logo": {
        "alt": "Buidler Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "href": "https://buidler.app/download",
          "label": "Download",
          "position": "right"
        },
        {
          "href": "https://invite.buidler.app/buidler",
          "label": "Join Community",
          "position": "right",
          "class": "join-community"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Buidler - Make Web3 Happen",
          "items": [
            {
              "label": "Website",
              "href": "https://buidler.app"
            },
            {
              "label": "Twitter",
              "href": "https://twitter/buidler_app"
            },
            {
              "label": "Youtube",
              "href": "https://www.youtube.com/channel/UCIkFTkBdbVgzQgw6braFaeg"
            },
            {
              "label": "Github",
              "href": "https://github.com/buidlerfoundation"
            }
          ]
        },
        {
          "title": "Product",
          "items": [
            {
              "label": "Download",
              "href": "https://buidler.app/download"
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "About",
              "href": "https://buidler.app"
            },
            {
              "label": "Terms",
              "href": "https://buidler.app/terms"
            },
            {
              "label": "Privacy",
              "href": "https://buidler.app/privacy"
            }
          ]
        }
      ]
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
