export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '376372a2': [() => import(/* webpackChunkName: '376372a2' */ '@site/docs/general/install-live-chat-plugin.mdx'), '@site/docs/general/install-live-chat-plugin.mdx', require.resolveWeak('@site/docs/general/install-live-chat-plugin.mdx')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '68ced570': [() => import(/* webpackChunkName: '68ced570' */ '/Users/mac/buidler-documentation/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/Users/mac/buidler-documentation/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/mac/buidler-documentation/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],
  '6bb41b40': [() => import(/* webpackChunkName: '6bb41b40' */ '@site/src/pages/404.js'), '@site/src/pages/404.js', require.resolveWeak('@site/src/pages/404.js')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'c1a0c411': [() => import(/* webpackChunkName: 'c1a0c411' */ '/Users/mac/buidler-documentation/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/Users/mac/buidler-documentation/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/mac/buidler-documentation/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],};
