name: Buidler Document CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     tags: ${{ steps.meta.outputs.tags }}
  #   steps:
  #     - name: Information
  #       run: |
  #         echo "The commit SHA is: $GITHUB_SHA"
  #         echo "The run id is: $GITHUB_RUN_ID" 
  #         echo "The GitHub Actor's username is: $GITHUB_ACTOR"

  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
  #       with:
  #         images: ${{ secrets.DOCKER_USERNAME }}/buidler-documentation
  #         tags: |
  #           type=sha,format=long

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         # labels: ${{ steps.meta.outputs.labels }}
  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Information
        run: |
          echo "The tags value is: sha-$GITHUB_SHA"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth deployment server
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Access deployment server
        id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: buidler-production
          zone: 'asia-southeast1-b'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: 'pwd && ls'
          # script: '${{ github.workspace }}/deployment/prod.sh aaa'

      - name: Access logs
        id: 'logs'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'