name: Buidler Document CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docker username ${{ secrets.DOCKER_USERNAME }}"
      - run: echo "Docker password ${{ secrets.DOCKER_PASSWORD }}."