name: Buidler Document CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Information
      run: |
        echo "The job_id is: $GITHUB_JOB"
        echo "The id of this action is: $GITHUB_ACTION"
        echo "The run id is: $GITHUB_RUN_ID" 
        echo "The GitHub Actor's username is: $GITHUB_ACTOR"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker build
      run: |
        echo "Docker username ${{ secrets.DOCKER_USERNAME }}"
